version: '3.8'

services:
  xampp:
    image: tomsik68/xampp:latest
    container_name: stream
    ports:
      - "8080:80"
      - "3306:3306"
    volumes:
      - ./php:/www
      - ./videos:/www/videos
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: no

